version: 2

updates:
    -   commit-message:
            include: "scope"
            prefix: "composer"
        directory: "/"
        ignore:
            -   dependency-name: "symfony/*"
            -   dependency-name: "sylius/*"
        package-ecosystem: "composer"
        schedule:
            interval: "weekly"
        versioning-strategy: "increase-if-necessary"
