setono_sylius_image_global:
    resource: "@SetonoSyliusImagePlugin/Resources/config/routes/global.yaml"

setono_sylius_image_shop:
    resource: "@SetonoSyliusImagePlugin/Resources/config/routes/shop.yaml"
    prefix: /{_locale}
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

setono_sylius_image_admin:
    resource: "@SetonoSyliusImagePlugin/Resources/config/routes/admin.yaml"
    prefix: /admin
